### ISSUE TITLE
augmentor.applyAugmentation() error

### ISSUE THREAD

**Issue by danielkovarik** [joheras/CLoDSA#8]
Hi CLoDSA team,

I am trying to make work your colab notebook on my data and I am not able to make it work through augmentor.applyAugmentation()

`---------------------------------------------------------------------------
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/joblib/externals/loky/process_executor.py", line 418, in _process_worker
    r = call_item()
  File "/usr/local/lib/python3.6/dist-packages/joblib/externals/loky/process_executor.py", line 272, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/joblib/_parallel_backends.py", line 567, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/joblib/parallel.py", line 225, in __call__
    for func, args, kwargs in self.items]
  File "/usr/local/lib/python3.6/dist-packages/joblib/parallel.py", line 225, in <listcomp>
    for func, args, kwargs in self.items]
  File "/usr/local/lib/python3.6/dist-packages/clodsa/augmentors/cocoLinearInstanceSegmentationAugmentor.py", line 46, in readAndGenerateInstanceSegmentation
    segmentation = [[x[0][0], x[0][1]] for x in cnts[0]]
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

IndexError                                Traceback (most recent call last)
<ipython-input-30-1d9c8eaf67b6> in <module>()
----> 1 augmentor.applyAugmentation()

5 frames
/usr/lib/python3.6/concurrent/futures/_base.py in __get_result(self)
    382     def __get_result(self):
    383         if self._exception:
--> 384             raise self._exception
    385         else:
    386             return self._result

IndexError: list index out of range`

Can you please direct me where is the problem?

**Comment by joheras** [comment]
Hi,

which notebook are you using? Is it possible for you to send a extract of your dataset to try to reproduce the problem?

**Comment by joheras** [comment]
I think that the problem was related to the issue raised in #7
I have updated a corrected version of Clodsa, you can install it using
pip install clodsa==1.2.34

Could you check if this solves your problem?

**Comment by danielkovarik** [comment]
Hi,

**Comment by danielkovarik** [comment]
Hi,

thanks a lot for your quick response. The update really fixed the applyAugmentation() error. But unfortunately, the augmented images have annotations on the wrong place. Look at the image attached. It is the visualization from the colab notebook. (When I visualize the original dataset, annotations are placed correctly.)

![clodsa](https://user-images.githubusercontent.com/35225229/64205626-bcd5f480-ce98-11e9-90b3-39bc87f6785a.png)

I use this notebook: [https://colab.research.google.com/github/joheras/CLoDSA/blob/master/notebooks/CLODSA_Instance_Segmentation.ipynb](url)

If you want to look at the original dataset I can send it to you in direct message if it it possible.

Thank you for your work!

Daniel

**Comment by joheras** [comment]
Hi,

Could you send me the dataset (or part of it) to joheras@gmail.com.

I will check the issue asap.
Best

**Comment by joheras** [comment]
I have fixed the problem. Update the version of clodsa and check that it works properly now.
Thanks.
Jónathan

**Comment by engmubarak48** [comment]
Hi, 

Is there any further progress on this bug, as I am still facing, thou I updated to the latest version.

**Comment by joheras** [comment]
Hi,
the problem faced by danielkovarik was solved. I am still working on the bug that you reported on the other issue.
